Bug 1187619: added -f option for getSchema.sh. Bug 1186414: changed package name to sblim-sfcb.

diff --git a/getSchema.sh.pre.in b/getSchema.sh.pre.in
--- a/getSchema.sh.pre.in
+++ b/getSchema.sh.pre.in
@@ -3,20 +3,56 @@
 
 trap "rm -f /tmp/cimv290.zip" exit 
 
-if test $# == 1; then
+function usage()
+{
+    echo usage: $1 [schemadir] >&2
+}
+
+args=`getopt f $*`
+
+if [ $? != 0 ]
+then
+    usage $0
+    exit 1
+fi
+
+set -- $args
+
+force=0
+while [ -n "$1" ]
+do
+  case $1 in
+      -f) force=1
+	  shift;;
+      --) shift;
+	  break;;
+  esac
+done
+
+if [ $# == 1 ]; then
     sfcbdir=$1
-elif test $# == 0; then
+elif [ $# == 0 ]; then
     sfcbdir=@datadir@/sfcb
 else
-    echo usage: $0 [schemadir]
+    usage $0
+    exit 1
 fi
 
 if [ -x /usr/bin/curl ] 
 then
-   if [ ! -f $sfcbdir/CIM/CIM_Schema.mof ]
+   if [ ! -f $sfcbdir/CIM/CIM_Schema.mof ] || [ $force == 1 ]
    then
       echo "Fetching CIM Schema from DMTF homepage ..."
-      [ -d $sfcbdir/CIM ] || mkdir -p $sfcbdir/CIM
+      if [ -d $sfcbdir/CIM ]
+      then
+	  rm -rf $sfcbdir/CIM
+	  if [ $? != 0 ]
+	  then
+	      echo "Failed to delete schema directory $sfcbdir/CIM" >&2
+	      exit 1
+	  fi
+      fi
+      mkdir -p $sfcbdir/CIM
       if [ $? == 0 ]; then
 	  /usr/bin/curl -o /tmp/cimv290.zip \
  http://www.dmtf.org/standards/cim/cim_schema_v29/CIM_V2.9.0Final-MOFs.zip &&
