Bugs: 1284983. Fixed interoperability problems in sfcb scripts.

diff --git a/getSchema.sh.pre.in b/getSchema.sh.pre.in
--- a/getSchema.sh.pre.in
+++ b/getSchema.sh.pre.in
@@ -3,14 +3,19 @@
 
 trap "rm -f /tmp/cimv290.zip" exit 
 
-function usage()
+usage()
 {
     echo usage: $1 [schemadir] >&2
 }
 
 args=`getopt f $*`
+rc=$?
 
-if [ $? != 0 ]
+if [ $rc = 127 ]
+then
+    echo "warning: getopt not found ...continue without syntax check"
+    args=$*
+elif [ $rc != 0 ]
 then
     usage $0
     exit 1
@@ -29,9 +34,9 @@ do
   esac
 done
 
-if [ $# == 1 ]; then
+if [ $# = 1 ]; then
     sfcbdir=$1
-elif [ $# == 0 ]; then
+elif [ $# = 0 ]; then
     sfcbdir=@datadir@/sfcb
 else
     usage $0
@@ -40,7 +45,7 @@ fi
 
 if [ -x /usr/bin/curl ] 
 then
-   if [ ! -f $sfcbdir/CIM/CIM_Schema.mof ] || [ $force == 1 ]
+   if [ ! -f $sfcbdir/CIM/CIM_Schema.mof ] || [ $force = 1 ]
    then
       echo "Fetching CIM Schema from DMTF homepage ..."
       if [ -d $sfcbdir/CIM ]
@@ -53,7 +58,7 @@ then
 	  fi
       fi
       mkdir -p $sfcbdir/CIM
-      if [ $? == 0 ]; then
+      if [ $? = 0 ]; then
 	  /usr/bin/curl -o /tmp/cimv290.zip \
  http://www.dmtf.org/standards/cim/cim_schema_v29/CIM_V2.9.0Final-MOFs.zip &&
 	  unzip -jd $sfcbdir/CIM /tmp/cimv290.zip &&
diff --git a/sfcbrepos.sh.in b/sfcbrepos.sh.in
--- a/sfcbrepos.sh.in
+++ b/sfcbrepos.sh.in
@@ -1,14 +1,18 @@
 #!/bin/sh
 
-function usage() 
+usage() 
 {
     echo "usage: $0 [-h] [-f] [-c cimschemadir] [-s stagingdir] [-r registrationdir] " 1>&2 
 }
 
-
 args=`getopt fhs:r:c: $*`
+rc=$?
 
-if [ $? != 0 ]
+if [ $rc = 127 ]
+then
+    echo "warning: getopt not found ...continue without syntax check"
+    args=$*
+elif [ $rc != 0 ]
 then
     usage $0
     exit 1
@@ -35,7 +39,7 @@ do
   esac
 done
 
-if [ "$help" == "1" ]
+if [ "$help" = "1" ]
 then
     usage
     echo -e "\t-h display help message"
@@ -56,7 +60,7 @@ then
 
     read response
 
-    if [ x$response == x ] || [ $response != yes ]
+    if [ x$response = x ] || [ $response != yes ]
     then
 	echo Keeping old data
 	exit 2
diff --git a/sfcbstage.sh.in b/sfcbstage.sh.in
--- a/sfcbstage.sh.in
+++ b/sfcbstage.sh.in
@@ -1,14 +1,18 @@
 #!/bin/sh
 
-function usage() 
+usage() 
 {
     echo "usage: $0 [-h] [ -s stagingdir] [ -r regfile ] [ mof ... ]  " 1>&2 
 }
 
-
 args=`getopt hr:s: $*`
+rc=$?
 
-if [ $? != 0 ]
+if [ $rc = 127 ]
+then
+    echo "warning: getopt not found ...continue without syntax check"
+    args=$*
+elif [ $rc != 0 ]
 then
     usage $0
     exit 1
@@ -31,7 +35,7 @@ do
   esac
 done
 
-if [ "$help" == "1" ]
+if [ "$help" = "1" ]
 then
     usage
     echo -e "\t-h display help message"
