Added /etc/sfcb configuration file support. Added SysV Init Script Support. Fixed sfcBroker SIGHUP sigmask problem.

diff --git a/sfcbstage.sh.in b/sfcbstage.sh.in
--- a/sfcbstage.sh.in
+++ b/sfcbstage.sh.in
@@ -56,14 +56,13 @@ fi
 if [ -n "$regfile" ]
 then
     cp $regfile $stagingdir/regs ||
-    echo "Error: could not copy registration files to $stagingdir" 1>&2 &&
-    exit 1
+    (echo "Error: could not copy registration files to $stagingdir" 1>&2 &&
+    exit 1)
 fi
 
 if [ -n "$*" ]
 then
-    cp $* $stagingdir/mofs &&
-    exit 0 ||
+    (cp $* $stagingdir/mofs && exit 0) ||
     echo "Error: could not find registration files" 1>&2    
     exit 1
 fi
