Bug 1186414: Additional work was necessary to make the renamed package work. Bug 1190811: Changes to support sfcbd in /usr/sbin.

diff --git a/sfcb.init-none.in b/sfcb.init-none.in
--- a/sfcb.init-none.in
+++ b/sfcb.init-none.in
@@ -1,19 +1,10 @@
 #!/bin/bash
 #
 # $Id$
-#
-### BEGIN INIT INFO
-# Provides:          sfcb
-# Default-Start:     3 5
-# Default-Stop:      0 1 2 6
-# Short-Description: Small Footprint CIM Broker Service
-# Description:       Manage the sfcb Service
-### END INIT INFO
+# 
+# Generic System V Init Script
 
-# Source function library.
-. /etc/rc.status
-
-echo $PATH | grep -q @bindir@ ||PATH=@bindir@:$PATH
+echo $PATH | grep -q @sbindir@ ||PATH=@sbindir@:$PATH
 
 if [ -z "$LD_LIBRARY_PATH" ] || echo $LD_LIBRARY_PATH | grep -qv @libdir@
 then
@@ -30,20 +21,23 @@ fi
 
 start() {
 	echo -n "Starting sfcb: "
-	startproc @bindir@/sfcbd -d
-	rcstatus -v
+	@sbindir@/sfcbd -d && echo "done." && return 0 ||
+	echo "failed."
+	return 1
 }	
 
 stop() {
 	echo -n "Shutting down sfcb: "
-	killproc sfcbd
-	rcstatus -v
+	killall sfcbd && echo "done." && return 0 ||
+	echo "failed."
+	return 1
 }
 
 reload() {
 	echo -n "Reloading sfcb configuration: "
-	killproc -HUP sfcbd
-	rcstatus -v
+	killall -HUP sfcbd && echo "done." && return 0 ||
+	echo "failed."
+	return 1
 }
 
 case "$1" in
@@ -54,8 +48,8 @@ case "$1" in
 	stop
 	;;
     status)
-	checkproc sfcbd
-	rc_status -v
+	echo -n "Checking SFCB status: "
+	ps --noheaders -C sfcbd || echo "stopped." 
 	;;
     restart)
     	stop
@@ -64,17 +58,8 @@ case "$1" in
     reload)
 	reload
 	;;
-    condrestart)
-	$0 status
-	if test $? = 0; then
-		$0 restart
-	else
-		rc_reset
-	fi
-	rc_status
-	;;
     *)
-	echo "Usage: sfcb {start|stop|status|reload|restart|condrestart}"
+	echo "Usage: sfcb {start|stop|status|reload|restart}"
 	exit 1
 	;;
 esac
diff --git a/sfcbrepos.sh.in b/sfcbrepos.sh.in
--- a/sfcbrepos.sh.in
+++ b/sfcbrepos.sh.in
@@ -81,32 +81,47 @@ fi
 if [ -d $stagingdir ] && [ -f $stagingdir/default.reg ] &&
 	[ -f $cimschemadir/CIM_Schema.mof ] 
 then
-    if rm -rf $registrationdir/repository.previous &&
-	mv -f $registrationdir/repository $registrationdir/repository.previous &&
-	mv -f $registrationdir/providerRegister $registrationdir/providerRegister.previous &&
-	mkdir -p $registrationdir/repository/root/cimv2 &&
-	cp $stagingdir/default.reg $registrationdir/providerRegister
+    if [ -d $registrationdir/repository ]
     then
-	if ls $stagingdir/regs/*.reg > /dev/null 2>&1
-	then
-	    if ! cat $stagingdir/regs/*.reg >> $registrationdir/providerRegister
-	    then
-		echo Failed copying the registration files. >&2
-		exit 1
-	    fi
+	rm -rf $registrationdir/repository.previous 2> /dev/null
+	mv -f $registrationdir/repository $registrationdir/repository.previous
+	if [ $? != 0 ]
+        then
+	    echo "Failed to remove old repository" >&2
+	    exit 1
 	fi
-	if ls $stagingdir/mofs/*.mof > /dev/null 2>&1
+    fi
+    if [ -f $registrationdir/providerRegister ]
+    then
+	mv -f $registrationdir/providerRegister $registrationdir/providerRegister.previous 
+	if [ $? != 0 ]
 	then
-	    if ! sfcbmof -o $registrationdir/repository/root/cimv2/classSchemas -I $cimschemadir -i CIM_Schema.mof $stagingdir/mofs/*.mof
-	    then
-		echo Failed compiling the MOF files. >&2
-		exit 1
-	    fi
+	    echo "Failed to remove old provider registry" >&2
+	    exit 1
 	fi
-	exit 0
-    else	
-	echo Failed to write sfcb registration files. >&2 
+    fi
+    mkdir -p $registrationdir/repository/root/cimv2 &&
+    cp $stagingdir/default.reg $registrationdir/providerRegister
+    if [ $? != 0 ]
+    then
+	echo "Failed to create default repository and registry" >&2
 	exit 1
+    fi
+    if ls $stagingdir/regs/*.reg > /dev/null 2>&1
+    then
+	if ! cat $stagingdir/regs/*.reg >> $registrationdir/providerRegister
+	then
+	    echo Failed copying the registration files. >&2
+	    exit 1
+	fi
+    fi
+    if ls $stagingdir/mofs/*.mof > /dev/null 2>&1
+    then
+	if ! sfcbmof -o $registrationdir/repository/root/cimv2/classSchemas -I $cimschemadir -i CIM_Schema.mof $stagingdir/mofs/*.mof
+	then
+	    echo Failed compiling the MOF files. >&2
+	    exit 1
+	fi
     fi
 else
     echo Could not find required staging files. Please check your setup. >&2
